server:
  port: 8130 #端口服务

spring:
  profiles:
    active: dev #环境配置
    application:
      name: service-oss #服务名

aliyun:
  oss:
    endpoint: 你的endpoint
    keyId: 你的阿里云keyid
    keySecret: 你的阿里云keysecret
    bucketName: srb-file